name: Build, Push and Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: learning/images
  IMAGE_NAME: devops-demo
  CONTAINER_NAME: devops-web

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: debugg session 
      run : |
        echo "role arn : ${{secrets.AWS_ROLE_ARN}}"
        echo "Repository: ${{ github.repository }}"
        echo "Ref: ${{ github.ref }}"

    - name: Print GitHub OIDC token claims
      uses: actions/github-script@v7
      with:
        script: |
          const idToken = await core.getIDToken('sts.amazonaws.com');
          console.log(idToken);

    - name: configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{secrets.AWS_ROLE_ARN}}
        aws-region: ${{env.AWS_REGION}}
        audience: sts.amazonaws.com
    
    - name: login to amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    
    - name: build docker image
      run: |
        docker build -t ${{env.IMAGE_NAME}} .
    
    - name: tag docker image
      run: |
        docker tag ${{env.IMAGE_NAME}}:latest ${{steps.login-ecr.outputs.registry}}/${{env.ECR_REPOSITORY}}:${{github.sha}}

    - name: push docker image to ECR
      run : |
        docker push ${{steps.login-ecr.outputs.registry}}/${{env.ECR_REPOSITORY}}:${{github.sha}}
      
    - name: SSH to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{secrets.EC2_HOST}}
        username: ${{secrets.EC2_USER}}
        key: ${{secrets.EC2_KEY}}
        script: |
          docker pull ${{steps.login-ecr.outputs.registry}}/${{env.ECR_REPOSITORY}}:${{github.sha}}
          docker stop ${{env.CONTAINER_NAME}} || true
          docker rm ${{env.CONTAINER_NAME}} || true
          docker run -d --name ${{env.CONTAINER_NAME}} -p 80:80 ${{steps.login-ecr.outputs.registry}}/${{env.ECR_REPOSITORY}}:${{github.sha}}